USE [master]
GO
/****** Object:  Database [AppFoundationDb]    Script Date: 31/07/2025 22:14:52 ******/
CREATE DATABASE [AppFoundationDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppFoundationDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AppFoundationDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppFoundationDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AppFoundationDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AppFoundationDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppFoundationDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AppFoundationDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AppFoundationDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AppFoundationDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AppFoundationDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AppFoundationDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [AppFoundationDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AppFoundationDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AppFoundationDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AppFoundationDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AppFoundationDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AppFoundationDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AppFoundationDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AppFoundationDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AppFoundationDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AppFoundationDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AppFoundationDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AppFoundationDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AppFoundationDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AppFoundationDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AppFoundationDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AppFoundationDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AppFoundationDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AppFoundationDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AppFoundationDb] SET  MULTI_USER 
GO
ALTER DATABASE [AppFoundationDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AppFoundationDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AppFoundationDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AppFoundationDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AppFoundationDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AppFoundationDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AppFoundationDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [AppFoundationDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AppFoundationDb]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NULL,
	[Description] [varchar](500) NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [varchar](50) NULL,
	[Email] [varchar](255) NULL,
	[Password] [varchar](500) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[User_Delete]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[User_Delete]
    @Id INT
AS
BEGIN
    DELETE FROM [dbo].[User]
    WHERE [Id] = @Id;
END;

GO
/****** Object:  StoredProcedure [dbo].[User_GetAll]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[User_GetAll]
AS
BEGIN
    SELECT [Id], [FullName], [Email], [Password]
    FROM [dbo].[User];
END;

GO
/****** Object:  StoredProcedure [dbo].[User_GetById]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[User_GetById]
    @Id INT
AS
BEGIN
    SELECT [Id], [FullName], [Email], [Password]
    FROM [dbo].[User]
    WHERE [Id] = @Id;
END;

GO
/****** Object:  StoredProcedure [dbo].[User_Insert]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[User_Insert]
    @FullName NVARCHAR(100),
    @Email NVARCHAR(100),
    @Password NVARCHAR(100)
AS
BEGIN
    INSERT INTO [dbo].[User] ([FullName], [Email], [Password])
    VALUES (@FullName, @Email, @Password);

    SELECT SCOPE_IDENTITY() AS NewUserId; -- returns the new Id
END;

GO
/****** Object:  StoredProcedure [dbo].[User_Update]    Script Date: 31/07/2025 22:14:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[User_Update]
    @Id INT,
    @FullName NVARCHAR(100),
    @Email NVARCHAR(100),
    @Password NVARCHAR(100)
AS
BEGIN
    UPDATE [dbo].[User]
    SET [FullName] = @FullName,
        Email=@Email,
        [Password] = @Password
    WHERE Id = @Id;
END;
GO
USE [master]
GO
ALTER DATABASE [AppFoundationDb] SET  READ_WRITE 
GO
