using System.Data;

using Dapper;

namespace RS.Dapper.Utility.Repositories.DapperExecutor;
/// <summary>
/// Provides generic methods to execute SQL commands and queries using Dapper.
/// </summary>
public interface IDapperExecutor
{
    /// <summary>
    /// Executes a command asynchronously that does not return a result set.
    /// Typically used for INSERT, UPDATE, DELETE statements or stored procedures.
    /// </summary>
    /// <param name="sql">The SQL command text or stored procedure name to execute.</param>
    /// <param name="param">An optional object containing parameters to pass to the command.</param>
    /// <param name="commandType">The type of command (Text or StoredProcedure). Default is Text.</param>
    /// <returns>The number of rows affected.</returns>
   public Task<int> ExecuteAsync(string sql, object? param = null, CommandType commandType = CommandType.StoredProcedure);
    /// <summary>
    /// Executes a command asynchronously that returns a single scalar value.
    /// Commonly used to retrieve autogenerated keys or single values from queries.
    /// </summary>
    /// <typeparam name="T">The expected return type of the scalar value.</typeparam>
    /// <param name="sql">The SQL command text or stored procedure name to execute.</param>
    /// <param name="param">An optional object containing parameters to pass to the command.</param>
    /// <param name="commandType">The type of command (Text or StoredProcedure). Default is Text.</param>
    /// <returns>The scalar result cast to type T.</returns>
    public Task<T?> ExecuteScalarAsync<T>(string sql, object? param = null, CommandType commandType = CommandType.StoredProcedure);
    /// <summary>
    /// Executes a query asynchronously that returns the first record or default if none found.
    /// Useful for retrieving a single entity or model from the database.
    /// </summary>
    /// <typeparam name="T">The type of the returned model or entity.</typeparam>
    /// <param name="sql">The SQL query or stored procedure name to execute.</param>
    /// <param name="param">An optional object containing parameters to pass to the query.</param>
    /// <param name="commandType">The type of command (Text or StoredProcedure). Default is Text.</param>
    /// <returns>The first record mapped to type T, or null if no records found.</returns>
    public Task<T?> QueryFirstOrDefaultAsync<T>(string sql, object? param = null, CommandType commandType = CommandType.StoredProcedure);
    /// <summary>
    /// Executes a query asynchronously that returns a collection of records.
    /// Useful for retrieving multiple entities or models from the database.
    /// </summary>
    /// <typeparam name="T">The type of the returned models or entities.</typeparam>
    /// <param name="sql">The SQL query or stored procedure name to execute.</param>
    /// <param name="param">An optional object containing parameters to pass to the query.</param>
    /// <param name="commandType">The type of command (Text or StoredProcedure). Default is Text.</param>
    /// <returns>An enumerable collection of records mapped to type T.</returns>
    public Task<IEnumerable<T>> QueryAsync<T>(string sql, object? param = null, CommandType commandType = CommandType.StoredProcedure);
    /// <summary>
    /// Executes a query asynchronously that returns multiple result sets.
    /// This method uses Dapper's QueryMultipleAsync and allows reading multiple sequences from a single command.
    /// </summary>
    /// <param name="sql">The SQL query or stored procedure name to execute.</param>
    /// <param name="param">An optional object containing parameters to pass to the query.</param>
    /// <param name="commandType">The type of command (Text or StoredProcedure). Default is Text.</param>
    /// <returns>
    /// A <see cref="SqlMapper.GridReader"/> instance that can be used to read multiple result sets.
    /// The caller is responsible for disposing the GridReader after reading all results.
    /// </returns>
    public Task<SqlMapper.GridReader> QueryMultipleAsync(string sql, object? param = null, CommandType commandType = CommandType.StoredProcedure);
}
